//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yerbowo.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class YerbaMateEco {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YerbaMateEco() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yerbowo.Infrastructure.Resources.YerbaMateEco", typeof(YerbaMateEco).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;To klasyczna, argentyńska mate, która produkowana jest w prowincji Misiones. Plantacja została założona przez polskiego imigranta, Jana Szychowskiego. Amanda od wielu lat zyskuje popularność na całym świecie i jest jedną z najchętniej pitych odmian. Susz zawiera gałązki i odrobinę naturalnego pyłu. Produkowany jest zupełnie bez środków chemicznej ochrony roślin oraz sztucznych nawozów. Dzięki temu napar jest jeszcze zdrowszy i bogatszy w potrzebne człowiekowi witaminy i minerały. Idealny dla miłośników k [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AmandaOrganica {
            get {
                return ResourceManager.GetString("AmandaOrganica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Łagodna w smaku i delikatna w działaniu klasyczna argentyńska mate. 
        ///Zawiera średniej wielkości listki, patyczki i pył..
        /// </summary>
        internal static string UnionSuave {
            get {
                return ResourceManager.GetString("UnionSuave", resourceCulture);
            }
        }
    }
}
