//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yerbowo.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class YerbaMateClassic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]   
		internal YerbaMateClassic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yerbowo.Infrastructure.Resources.YerbaMateClassic", typeof(YerbaMateClassic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasyczna argentyńska yerba mate o delikatnym aromacie i łagodnym, słodkawym smaku. Składa się z listków i gałązek, bardzo mało pylista i umiarkowanie pobudzająca, przeznaczona do codziennej konsumpcji. Amanda pochodzi z plantacji La Cauchera ze słynnej prowincji Misiones należącej do polskich emigrantów Szychowskich. Jedna z najpopularniejszych marek yerba mate w Argentynie.
        ///
        ///Sposób użycia:
        ///1. Nasyp do 3/4 objętości naczynia susz yerba mate i przykryj ręką górną część naczynia.
        ///2. Odwróć naczynie i wst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Amanda {
            get {
                return ResourceManager.GetString("Amanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YERBA MATE BARAO DE COTEGIPE PREMIUM - DAJ SIĘ PONIEŚĆ ENERGII
        ///Yerba mate Barao de Cotegipe Premium, to mate hodowana i tworzona według receptur brazylijskich. Na susz składają się bardzo drobno zmielone listki wysokogatunkowego ostrokrzewu paragwajskiego oraz drobne patyczki i gałązki - to sprawia, że jest to yerba mate premium. Zmielenie zielonych fragmentów rośliny niemal na pył sprawia, że brazylijska yerba mate jest niezwykle intensywna w działaniu i wyrazista w smaku. W utrzymaniu właściwości przez d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaraoDeCotegipePremium {
            get {
                return ResourceManager.GetString("BaraoDeCotegipePremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yerba mate Campesino Clasica to aromatyczna paragwajska mate bez dodatków. Posiada drobno zmielone listki i patyczki, dzięki czemu możemy w pełni cieszyć się jej mocą..
        /// </summary>
        internal static string CampesinoClasica {
            get {
                return ResourceManager.GetString("CampesinoClasica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentyńska mate, której susz składa się głównie z drobno ciętych listków i dużej ilości pyłu. 
        ///Dość delikatna w smaku, jednak nie zmniejsza się przez to moc pobudzenia. 
        ///Polecana zarówno dla osób rozpoczynających przygodę z yerbą, jak i dla wprawionych yerboholików..
        /// </summary>
        internal static string NoblezaGauchaMolienda {
            get {
                return ResourceManager.GetString("NoblezaGauchaMolienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YERBA MATE PIPORE TERERE 500G
        ///Dostępność:	Dostępny
        ///Czas wysyłki:	2 dni
        ///Koszt dostawy:	od 8,99zł - zobacz wszystkie
        ///od 70,00zł darmowa wysyłka
        ///
        ///Cena:  23,95zł  
        ///
        ///1
        ///szt.
        ///OPIS
        ///OPINIE
        ///YERBA MATE PIPORE TERERE - ORZEŹWIAJĄCA NUTKA POBUDZENIA
        ///Yerba mate Pipore, to argentyńska mate przeznaczona do przygotowania w formie terere, czyli na zimno. Pipore yerba stworzona została z myślą o tych, którzy chcą poczuć prawdziwie mroźne orzeźwienie. Yerba Pipore przygotowana w formie terere, doskonale gasi pragn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PiporeTerere {
            get {
                return ResourceManager.GetString("PiporeTerere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosamonte to najstarsza argentyńska marka yerba mate. Od lat znana i ceniona na całym świecie, codziennie zyskuje nowe rzesze zwolenników. Na susz składają się drobno cięte listki, gałązki oraz naturalny pył. Jest niezwykle intensywna w smaku, jak przystało na tradycyjną argentyńską mate. Poza wyraźną nutą ostrokrzewu paragwajskiego, wyczuwalny jest także zapach drzewa różanego. W jego towarzystwie bowiem leżakują zbiory tej wyjątkowej yerby. Uzyskany napar jest bardzo energetyzujący. Działa zdecydowanie mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rosamonte {
            get {
                return ResourceManager.GetString("Rosamonte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YERBA MATE SARA ROJA - EKSCYTUJĄCA MIESZANKA SMAKU
        ///Yerba mate Sara Roja, to klasyczna brazylijska yerba mate, choć produkowana jest głównie na rynek urugwajski. Charakteryzuje się wyrazistym smakiem i mocnym, długo utrzymującym się działaniem. Ta brazylijska yerba mate składa się z bardzo drobno zmielonych liści, a także prawie w ogóle nie zawiera patyków. Można zalewać ją nawet do 8 razy, ponieważ dzięki swojej intensywności, długo utrzymuje smak i aromat. Aby rozkoszować się w pełni mocą tego naparu, wys [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaraRojaTradicionalSinPalo {
            get {
                return ResourceManager.GetString("SaraRojaTradicionalSinPalo", resourceCulture);
            }
        }
    }
}
