//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yerbowo.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class YerbaMateSelected {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YerbaMateSelected() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yerbowo.Infrastructure.Resources.YerbaMateSelected", typeof(YerbaMateSelected).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YERBA MATE PAJARITO SELECCION - WYJĄTKOWA INTENSYWNOŚĆ SMAKU
        ///Ta wyjątkowa, sezonowana odmiana, jaką jest Yerba mate Pajarito Seleccion wywodzi się prosto z Paragwaju. Yerba Pajarito zawiera starannie selekcjonowane listki oraz dodatek drobnych gałązek. Spośród innych gatunków Pajarito yerba mate wyróżnia się wydłużonym okresem leżakowania, trwającym aż dwa lata. W tym czasie yerba Pajarito seleccion nabiera niezwykłej mocy, która stawia ją wśród najsilniejszych suszów dostępnych na rynku. Ma niezwykle inte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PajaritoSeleccionEspecial {
            get {
                return ResourceManager.GetString("PajaritoSeleccionEspecial", resourceCulture);
            }
        }
    }
}
