//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yerbowo.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class YerbaMateSets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YerbaMateSets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yerbowo.Infrastructure.Resources.YerbaMateSets", typeof(YerbaMateSets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;western&quot;&gt;&lt;span&gt;Zestaw zawierający Amandę Roja 500G, ceramiczne&amp;nbsp;matero oraz bombillę.&amp;nbsp;&lt;/span&gt;&lt;/p&gt;&lt;p class=&quot;western&quot;&gt;&lt;span&gt;Amanda&amp;nbsp;produkowana jest w Argentynie przez potomków polskich emigrantów. Znana jest na całym świecie ze swojej niezwykłej jakości. Susz praktycznie pozbawiony jest pyłu i gałązek. Grubo cięte listki uwalniają moc nawet przy wielokrotnym zalewaniu. Ma łagodny, pozbawiony goryczki smak. Sprawdzi się dla miłośników świeżych, roślinnych i przyjemnie trawiastych odmian [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AmandaRojaWithCeramicMateCupAndBombilla {
            get {
                return ResourceManager.GetString("AmandaRojaWithCeramicMateCupAndBombilla", resourceCulture);
            }
        }
    }
}
