//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yerbowo.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class YerbaMateFruits {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YerbaMateFruits() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yerbowo.Infrastructure.Resources.YerbaMateFruits", typeof(YerbaMateFruits).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Yerba mate CBSe Silueta Naranja o niezwykłym aromacie pomarańczy&lt;/h2&gt;&lt;p&gt;&lt;b&gt;Yerba mate CBSe Silueta Naranja&lt;/b&gt; to doskonałe połączenie yerba mate oraz świeżych ziół. Odmianę &lt;b&gt;yerba mate CBSe Maranja&lt;/b&gt; wyróżnia niezwykły aromat pomarańczy, który idealnie komponuje się z pozostałymi składnikami tej mieszanki &lt;b&gt;yerba mate. Cena&lt;/b&gt; produktów marki CBSe należy do bardzo atrakcyjnych, dlatego każdy może cieszyć się tym niezwykłym smakiem. Bowiem &lt;b&gt;yerba mate CBSe Maranja&lt;/b&gt; to idealna propozycja dla p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CbseSiluetaNaranjaOrange {
            get {
                return ResourceManager.GetString("CbseSiluetaNaranjaOrange", resourceCulture);
            }
        }
    }
}
